version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  book-app:
    build: .
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "Pa55w0rd2021"
      Database: "mcvtestDb"
    ports: 
      - "8090:80"
    depends_on:
      - "mssql-server"